[project]
name = "ejercicio-04-combinados"
version = "0.1.0"
description = "Ejercicio 04: ParÃ¡metros Combinados"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.0",
    "uvicorn[standard]>=0.40.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
