[project]
name = "ejercicio-03-validadores"
version = "0.1.0"
description = "Ejercicio: Validadores Personalizados"
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2.12",
]

[tool.uv]
dev-dependencies = []
