# ============================================
# DOCKER COMPOSE - Proyecto API de Saludo
# ============================================

version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"       # Mapea contenedor a host
    volumes:
      - .:/app:cached     # Monta tu proyecto, :cached ayuda en Windows
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
