[project]
name = "ejercicio-01-response-models"
version = "1.0.0"
description = "Ejercicio de Response Models"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "pydantic[email]>=2.10.0",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.4.0",
    "httpx>=0.29.0",
]
