[project]
name = "ejercicio-01-basemodel"
version = "0.1.0"
description = "Ejercicio: BaseModel BÃ¡sico"
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2.12",
]

[tool.uv]
dev-dependencies = []
